# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
  - faq/deploy_ap
  - faq/inform_user
  - faq/inform_admin
  - faq/q_ap
  - faq/q_ap_copy
  - faq/q_ap_lesson
  - faq/q_ap_lt_delete
  - faq/q_ap_quizadd
  - faq/q_ap_rearrange
  - faq/q_resource_learn_add
  - faq/q_ap_rename
  - faq/q_ap_share
  - faq/q_ap_shareable
  - faq/q_ap_topic
  - faq/q_category
  - faq/q_forms
  - faq/q_ls
  - faq/q_ls_access
  - faq/q_ls_more
  - faq/q_resource_type
  - faq/q_template_ap
  - faq/satisfied
  - faq/unsatisfied
  - faq/q_followup
  - faq/failed_ap
  - faq/prompt_cs
  - faq/fallback
  - faq/ask_follow_up
  - faq/redirection
  - faq/misunderstood
  - faq/follow_up_after_answer
  - faq/negative_follow_up
  - faq/positive_follow_up